name: CollectMetadataSelf
on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    types: ["merge", "open"]
    branches: ["pr_push"]
  workflow_dispatch:

jobs:
  Collect-Metadata:
    name: Collect-Metadata
    runs-on: ubuntu-latest
    needs: []
    steps:
      - name: fast_checkout
        uses: actions/checkout@v4

      - name: collect-mindie
        id: collect-mindie
        uses: lb-actions/openlibing-metadata-collect@v1.0.0
        with:
          testcase-path: ./tests
          # pytest-config-file: ./resource/pytest_mindie.ini

      - name: generate-xml
        run: |
          cat > /tmp/test_result_WejsKsE.xml << 'EOF'
          <?xml version="1.0" ?>
          <testsuites name="Uniautos test">
              <testsuite name="uniautos" tests="2" skipped="0" failures="0" time="41.0" timestamp="2026-07-07 07:07:07">
                  <testcase classname="TestBatchInvariant" name="test_enable_batch_invariant_mode_ascendc_path" time="5.620"/>
                  <testcase classname="TestBatchInvariant" name="test_override_envs_for_invariance" time="5.620"/>
              </testsuite>
          </testsuites>
          EOF


      - name: print-metadata-filepath
        run: |
          echo "mindie: ${{ steps.collect-mindie.outputs.metadata-output-path }}"

      - name: print-content
        run: cat ${{ steps.collect-mindie.outputs.metadata-output-path }}

      - name: openlibing-upload-reports-style1
        uses: lb-actions/openlibing-upload-reports@v1.0.0
        with:
          files: >
            ${{ steps.collect-mindie.outputs.metadata-output-path }}
            /tmp/test_result_WejsKsE.xml
          openlibing-secret: ${{ secrets.scheduler_secret }}
          github-token: ${{ secrets.mytoken }}


      # - name: openlibing-upload-reports-style1
      #   uses: lb-actions/openlibing-upload-reports@v1.0.0
      #   with:
      #     files: "/tmp/test_result_WejsKsE.xml /tmp/metadata_presomke.xml"
      #     openlibing-secret: ${{ secrets.scheduler_secret }}
      #     pipeline-id: ${{ github.run_id }}
      #     pipeline-run-id: ${{ github.run_id }}
      #     job-id: ${{ steps.get-job-id.outputs.job-id }}
